name: Bnan Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-vcpkg from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-vcpkg

      - name: Install build tools (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Setup build tools (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build vcpkg dependencies
        run: cargo vcpkg build

      - name: Set VCPKG_ROOT
        shell: bash
        run: echo "VCPKG_ROOT=${{ github.workspace }}/target/vcpkg/" >> $GITHUB_ENV

      - name: Print vcpkg failure logs
        if: failure()
        run: find target/vcpkg/buildtrees -name "*.log" -print0 | xargs -0 cat

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose